// Generated by ReScript, PLEASE EDIT WITH CARE


var count = {
  contents: 0
};

function updateCount(steps) {
  count.contents = count.contents + steps | 0;
  
}

function getClassName(count) {
  if (count === 0) {
    return "count-zero";
  } else if (count > 0) {
    return "count-positive";
  } else {
    return "count-negative";
  }
}

function renderCountTextView(count, className) {
  var ele = document.getElementById("count");
  ele.innerText = "Count is " + String(count);
  ele.className = "count " + className;
  
}

function renderView(steps) {
  updateCount(steps);
  var count$1 = count.contents;
  var className = getClassName(count$1);
  return renderCountTextView(count$1, className);
}

function plusOne(param) {
  return renderView(1);
}

function minusOne(param) {
  return renderView(-1);
}

var plusBtn = document.getElementById("plus-one");

var minusBtn = document.getElementById("minus-one");

plusBtn.addEventListener("click", plusOne);

minusBtn.addEventListener("click", minusOne);

export {
  count ,
  updateCount ,
  getClassName ,
  renderCountTextView ,
  renderView ,
  plusOne ,
  minusOne ,
  plusBtn ,
  minusBtn ,
  
}
/* plusBtn Not a pure module */
